In [1]:
import tushare as ts

In [4]:
sz50s = ts.get_sz50s()
sz50s.head()

         date    code  name
0  2018-03-15  600000  浦发银行
1  2018-03-15  600016  民生银行
2  2018-03-15  600019  宝钢股份
3  2018-03-15  600028  中国石化
4  2018-03-15  600029  南方航空

In [5]:
allStock = ts.get_today_all()
allStock.head()

[Getting data:]############################################################

,code,name,changepercent,trade,open,high,low,settlement,volume,turnoverratio,amount,per,pb,mktcap,nmc
0,603999,读者传媒,-1.626,7.26,7.37,7.37,7.21,7.38,1784994.0,0.77474,1.299070e+07,25.034,2.507,4.181760e+05,1.672704e+05
1,603998,方盛制药,0.000,9.43,0.00,0.00,0.00,9.43,0.0,0.00000,0.000000e+00,58.938,4.066,4.063731e+05,4.009605e+05
2,603997,继峰股份,-1.550,11.43,11.56,11.56,11.35,11.61,3129670.0,0.49677,3.575766e+07,19.373,4.366,7.289130e+05,7.200900e+05
3,603996,中新科技,0.232,17.28,17.09,17.44,17.02,17.24,3196827.0,3.09545,5.531282e+07,44.308,3.652,5.186592e+05,1.784592e+05
4,603993,洛阳钼业,3.614,9.46,9.32,9.64,9.12,9.13,360724680.0,2.78472,3.393773e+09,157.667,5.481,2.043288e+07,1.225423e+07

In [10]:
sz50List = sz50s.set_index('code')
sz50List.head()

              date  name
code
600000  2018-03-15  浦发银行
600016  2018-03-15  民生银行
600019  2018-03-15  宝钢股份
600028  2018-03-15  中国石化
600029  2018-03-15  南方航空

In [11]:
allList = allStock.set_index('code')
allList.head()

,name,changepercent,trade,open,high,low,settlement,volume,turnoverratio,amount,per,pb,mktcap,nmc
code,,,,,,,,,,,,,,
603999,读者传媒,-1.626,7.26,7.37,7.37,7.21,7.38,1784994.0,0.77474,1.299070e+07,25.034,2.507,4.181760e+05,1.672704e+05
603998,方盛制药,0.000,9.43,0.00,0.00,0.00,9.43,0.0,0.00000,0.000000e+00,58.938,4.066,4.063731e+05,4.009605e+05
603997,继峰股份,-1.550,11.43,11.56,11.56,11.35,11.61,3129670.0,0.49677,3.575766e+07,19.373,4.366,7.289130e+05,7.200900e+05
603996,中新科技,0.232,17.28,17.09,17.44,17.02,17.24,3196827.0,3.09545,5.531282e+07,44.308,3.652,5.186592e+05,1.784592e+05
603993,洛阳钼业,3.614,9.46,9.32,9.64,9.12,9.13,360724680.0,2.78472,3.393773e+09,157.667,5.481,2.043288e+07,1.225423e+07

In [19]:
sz50_basic = allStock[allStock['code'].isin(sz50s['code'])]
sz50_basic.head()

,code,name,changepercent,trade,open,high,low,settlement,volume,turnoverratio,amount,per,pb,mktcap,nmc
4,603993,洛阳钼业,3.614,9.46,9.32,9.64,9.12,9.13,360724680.0,2.78472,3.393773e+09,157.667,5.481,2.043288e+07,1.225423e+07
427,601989,中国重工,0.181,5.53,5.49,5.56,5.48,5.52,74166034.0,0.40392,4.092882e+08,145.526,1.656,1.265253e+07,1.015400e+07
428,601988,中国银行,0.000,4.17,4.15,4.19,4.15,4.17,113539378.0,0.05387,4.729864e+08,7.722,0.889,1.227597e+08,8.788922e+07
429,601985,中国核电,-0.279,7.15,7.14,7.18,7.12,7.17,15173864.0,0.35875,1.084070e+08,24.826,2.580,1.112928e+07,3.024200e+06
452,601881,中国银河,-1.463,10.10,10.23,10.24,9.97,10.25,21916422.0,1.78395,2.214413e+08,18.704,1.596,1.023863e+07,1.240816e+06

In [24]:
sz50_basic[(sz50_basic.per<20) & (sz50_basic.pb<2) & ('银行' not in sz50_basic.name)]

,code,name,changepercent,trade,open,high,low,settlement,volume,turnoverratio,amount,per,pb,mktcap,nmc
428,601988,中国银行,0.000,4.17,4.15,4.19,4.15,4.17,113539378.0,0.05387,4.729864e+08,7.722,0.889,1.227597e+08,8.788922e+07
452,601881,中国银河,-1.463,10.10,10.23,10.24,9.97,10.25,21916422.0,1.78395,2.214413e+08,18.704,1.596,1.023863e+07,1.240816e+06
462,601818,光大银行,-0.235,4.24,4.23,4.26,4.22,4.25,60883162.0,0.15293,2.583702e+08,6.730,0.812,2.225541e+07,1.687963e+07
466,601800,中国交建,-0.305,13.09,13.00,13.16,12.85,13.13,15379618.0,0.13092,2.003497e+08,13.495,1.374,2.117273e+07,1.537713e+07
482,601669,中国电建,-0.141,7.10,7.09,7.12,7.07,7.11,7878608.0,0.08207,5.585959e+07,15.062,1.522,1.086231e+07,6.816000e+06
483,601668,中国建筑,0.112,8.90,8.85,8.92,8.84,8.89,65283943.0,0.21958,5.801550e+08,9.271,1.403,2.670000e+07,2.646122e+07
506,601398,工商银行,0.311,6.46,6.41,6.47,6.40,6.44,151961987.0,0.05636,9.794265e+08,8.390,1.149,2.302384e+08,1.741695e+08
507,601390,中国中铁,0.133,7.52,7.48,7.53,7.47,7.51,14726777.0,0.08035,1.104978e+08,14.545,1.241,1.717891e+07,1.378268e+07
518,601328,交通银行,0.156,6.44,6.41,6.45,6.41,6.43,49968458.0,0.12731,3.212223e+08,7.236,0.799,4.782520e+07,2.527756e+07
522,601288,农业银行,0.978,4.13,4.07,4.14,4.07,4.09,385821742.0,0.13121,1.587713e+09,7.509,1.012,1.341400e+08,1.214448e+08
527,601229,上海银行,-0.330,15.10,15.10,15.19,15.06,15.15,13226022.0,0.35680,1.999282e+08,5.785,0.949,1.178674e+07,5.597411e+06
535,601211,国泰君安,0.111,18.02,17.96,18.05,17.87,18.00,10410831.0,0.21998,1.870444e+08,14.893,1.433,1.570252e+07,8.528318e+06
541,601186,中国铁建,0.194,10.34,10.27,10.37,10.27,10.32,12543853.0,0.10905,1.294036e+08,10.039,1.071,1.404125e+07,1.189436e+07
544,601169,北京银行,-0.276,7.22,7.20,7.24,7.20,7.24,14511587.0,0.07952,1.047521e+08,6.224,0.865,1.526523e+07,1.317506e+07
546,601166,兴业银行,0.170,17.68,17.61,17.71,17.59,17.65,38872054.0,0.20403,6.863766e+08,6.383,0.960,3.672877e+07,3.368453e+07
584,601006,大秦铁路,0.556,9.05,9.00,9.07,8.97,9.00,22117326.0,0.14877,1.994347e+08,18.854,1.381,1.345445e+07,1.345445e+07
590,600999,招商证券,0.000,17.30,17.20,17.39,17.18,17.30,6357933.0,0.12966,1.098769e+08,19.072,1.830,1.158998e+07,8.483400e+06
627,600919,江苏银行,-0.933,7.43,7.50,7.51,7.42,7.50,25795304.0,0.43544,1.925562e+08,7.582,0.966,8.577526e+06,4.401516e+06
686,600837,海通证券,0.165,12.14,12.08,12.14,12.04,12.12,19703531.0,0.24349,2.383763e+08,17.343,1.203,1.396306e+07,9.823847e+06
876,600606,绿地控股,-1.279,7.72,7.76,7.84,7.67,7.82,87719635.0,2.72137,6.791668e+08,13.085,1.613,9.393815e+06,2.488440e+06
1266,600104,上汽集团,-0.271,36.77,36.72,37.09,36.60,36.87,11195586.0,0.09732,4.120524e+08,12.666,1.993,4.296009e+07,4.229812e+07
1313,600048,保利地产,0.137,14.59,14.57,14.68,14.41,14.57,76064766.0,0.64811,1.107323e+09,13.264,1.837,1.730147e+07,1.712332e+07
1317,600036,招商银行,0.428,30.52,30.21,30.68,30.21,30.39,24195976.0,0.11729,7.372853e+08,12.407,1.757,7.697097e+07,6.295954e+07
1323,600028,中国石化,0.000,6.42,6.39,6.45,6.37,6.42,78418687.0,0.08206,5.033763e+08,16.762,1.085,7.772772e+07,6.134809e+07
1331,600019,宝钢股份,0.105,9.54,9.48,9.59,9.37,9.53,80977673.0,0.36659,7.684667e+08,17.345,1.343,2.124359e+07,2.107360e+07
1334,600016,民生银行,-0.239,8.36,8.35,8.38,8.33,8.38,51700708.0,0.17495,4.316692e+08,6.382,0.845,3.050175e+07,2.470528e+07
1344,600000,浦发银行,0.000,12.39,12.35,12.41,12.34,12.39,17287774.0,0.06151,2.139721e+08,5.154,0.939,3.636723e+07,3.482056e+07

(50, 15)